  const  MAIN_URL="https://sflt.herokuapp.com"
//  const MAIN_URL="http://192.168.196.63:3001"
export const APPEALS_URL=`${MAIN_URL}/api/appeals`
export const IMAGE_URL=`${MAIN_URL}/image`
export const MEDIA_URL=`${MAIN_URL}/api/media/image`
export const MEDIA_IMAGE_URL=`${MAIN_URL}/media/image`
export const PAYMENT_URL=`${MAIN_URL}/api/stripe-payment` 
export const DONORS_URL=`${MAIN_URL}/api/donors`
export const DONORS_UPDATE_URL=`${MAIN_URL}/api/donors-update`
export const AVATAR_URL=`${MAIN_URL}/avatar`